version: '3'

services:
  # Serviço Workspace com todas as ferramentas necessárias 
  workspace:
    build:
      context: .
      dockerfile: Dockerfile.workspace
    container_name: laravel_workspace
    working_dir: /var/www
    volumes:
      - ./vivo:/var/www
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_DATABASE: vivo
      DB_USERNAME: laravel
      DB_PASSWORD: secret
    networks:
      - app-network

  # Serviço para o servidor web Nginx
  nginx:
    image: nginx:latest
    container_name: nginx_server
    ports:
      - "80:80"
    volumes:
      - ./vivo:/var/www
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - workspace
    networks:
      - app-network

  # Serviço para o banco de dados MySQL
  mysql:
    image: mysql:latest
    container_name: mysql_db
    environment:
      MYSQL_DATABASE: vivo
      MYSQL_USER: laravel
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app-network

  # Serviço para o PhpMyAdmin
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin_container
    environment:
      PMA_HOST: mysql
    ports:
      - "8080:80"
    depends_on:
      - mysql
    networks:
      - app-network

volumes:
  mysql_data:

networks:
  app-network:
    driver: bridge
